### ISSUE TITLE
Support more formats for packing blobs

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#1090]
Possible examples (identified by mimeType in the Entry):
- JSON
- parquet
- arrow
- ...?

**Comment by Affie** [comment]
We currently have these:
- JSON: "application/octet-stream/json"
- BSON: "application/bson"
- PNG: "image/png"
- JPG: "image/jpeg"
- LAS: "application/octet-stream; ext=las" (maybe rename to "application/vnd.las")

- [ ] ARROW: "application/vnd.apache.arrow.file"
- [ ] PARQUET: "application/vnd.apache.parquet"
