### ISSUE TITLE
Implement 2D matrices in JSON2.jl and skip the PackedVariableData data type.

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#12]

**Comment by dehann** [comment]
JSON in other languages will not support `Array{Float64,2}` yet so is it worth restricting ourselves to `vec(M)::Array{Float64,1}` and then also carry a `dimM::Tuple{Int, Int, ...}` around as well?

**Comment by dehann** [comment]
We're going with JSON.jl as per NavAbility vote.  We are also now TensorCast to make array of arrays where possible.  My understanding is trying to jam a matrix in JSON is not the way forward.

**Comment by dehann** [comment]
Also see features like overloading `JSON.lower` on user specific types, which might be a really good way to resolve all our specific CJL specific needs. xref #590
