### ISSUE TITLE
Is the local implementaion GraphsDFG _copyIntoGraphs not more efficient than the generic one

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#123]
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/735e8ec6c3cf23a46a45e622db4ee45ef7a411f2/src/GraphsDFG/services/GraphsDFG.jl#L299

**Comment by GearsAD** [comment]
Probably minimally so, but benefit of having one function to maintain in AbstractDFG.jl is nice. Okay to close this?
