### ISSUE TITLE
Add documentation for plotting

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#126]
As per Slack chat - document dfgplot and toDot

![image](https://user-images.githubusercontent.com/6854507/65819407-d8a39080-e1e1-11e9-8824-4da2df4dd476.png)

**Comment by Affie** [comment]
Thanks @GearsAD, https://juliarobotics.org/DistributedFactorGraphs.jl/latest/DrawingGraphs/
