### ISSUE TITLE
Graph level small data for robot/user/session

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#133]
What about adding graph level small data to all the DFG types?
eg in LightDFG:
```julia
mutable struct LightDFG{T <: AbstractParams, V <: AbstractDFGVariable, F <:AbstractDFGFactor} <: AbstractDFG
    g::FactorGraph{Int, V, F}
    description::String
    userId::String
    robotId::String
    sessionId::String
    addHistory::Vector{Symbol} #TODO: Discuss more - is this an audit trail?
    solverParams::T # Solver parameters
    **smallData::Dict{Symbol, String}**
end
```
Maybe a Dict{Symbol, String} for easier serialization?

**Comment by GearsAD** [comment]
Example in #140 - it will help us address user/robot/session data too, which will be needed soon.

**Comment by GearsAD** [comment]
TODO:
- MetaGraphDFG and SymbolDFG must implement
- FileDFG must serialize/deserialize
- CloudGraphsDFG must serialize/deserialize

**Comment by Affie** [comment]
Partially implemented already.
