### ISSUE TITLE
Setup Neo4j on travis

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#146]

**Comment by Affie** [comment]
@GearsAD I saw you got it to run with trusty and added changing password, see build: https://travis-ci.org/JuliaRobotics/DistributedFactorGraphs.jl/jobs/598521164#L466
Looks like a travis bug: https://travis-ci.community/t/neo4j-service-start-is-probably-broken-by-change-to-xenial-as-the-default-build-environment/5381

**Comment by GearsAD** [comment]
Cool, in #138 with your changes, we can close when that merges.
