### ISSUE TITLE
updateVariableSolverData! behavior

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#166]
@GearsAD, From tests I see we may have different views on what  `updateVariableSolverData!` does.
I see update as only add to and not delete existing keys:
- If `var1` has only :default and you update it with `var2` that only has :second. `var1` should get a :second and :default should remain.
- If `var1` has only :default and you update it with `var2` that has :defualt. `var1` :default should be replaced/updated 

https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/b110db99e1a25fedb68f8589d6122cc53ea3aaa7/test/iifInterfaceTests.jl#L200-L203

cc @dehann

**Comment by GearsAD** [comment]
No, because in that case there is no way to delete. We've discussed this and an update is an atomic transaction that performs a complete update, shouldn't make it do unexpected things.

**Comment by GearsAD** [comment]
I'm not sure why you want to make it smarter than a simple CRUD update, I can't see the benefit.

**Comment by Affie** [comment]
I though the idea was to have different solves. So if one dfg runs solve1 and another solve2 what do you keep, solve1 or solve2? I thought both. If you just replace the whole dictionary it will update just one. So it is still a complete update but of one solve and not all solves. 
But let me know if i misunderstand the whole solves thing.

**Comment by Affie** [comment]
> No, because in that case there is no way to delete

Then add a delete. Update should not delete, it should update.

**Comment by GearsAD** [comment]
Okay - so the concern is that on datastructures CRUD behavior is standard, and we're deviating from how you generally treat a dictionary. It's fair that you want to merge, so how about this going to change the name and keep the behavior the same.
