### ISSUE TITLE
Should :default => VariableNodeData be populated in DFGVariable constructor

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#202]
referring to `:default => VariableNodeData{T}()`
I would think that creating an empty dictionary is more appropriate since IIF will populate the values regardless. I'm experimenting with ways to implement other algorithms and turning `:default` off completely. 
I just want to know if there was a good reason for populating it.

**Comment by dehann** [comment]
I don't have any meaningful suggestions on this, so either way is good with me.

**Comment by dehann** [comment]
The only reason I can see for populating it is to force a type T.  As long there is not an anonymous type instability later when the Dict is populated it should be good.

**Comment by dehann** [comment]
initially populating the Dict with an abstract would also be bad

**Comment by Affie** [comment]
About your comment from slack:

> in general yes its bad to have solverDataDict contain different softtypes -- although in this case I think that will be rare.  Only if we use different variable softtypes in different supersolves.  My suggestion is just ot raise a warning at create time if that occurs and then allow it to be slow.  All other cases should have solverDataDict  contain all the same softtype -- e.g. Pose2, Point2 ...

Do you see a case where solverDataDict can contain different soft types.

**Comment by GearsAD** [comment]
There isn't really a strong reason to populate it, to be honest. I believe it's populated because before softtype specialization and the solver dictionary, there was always a value. I _think_ if we remove the default value then things will blow up (a lot of code just expects a default value to be there), but we can clean that up if it's important to your testing?

**Comment by Affie** [comment]
I removed it and nothing broke in IIF tests. `addVariable!` overwrites :default (and :parametric) if its there.
