### ISSUE TITLE
isFactor true on variable

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#221]
Hi,  found a possible bug in that isFactor is returning true for variables:
```julia
julia> isFactor(fg,:x0)
true
```

This is using GraphsDFG.

**Comment by dehann** [comment]
same is happening in reverse:
```julia
julia> isVariable(fg,:x0f1)
true
```

**Comment by GearsAD** [comment]
Ah, this is because they both use exists, will make a small fix tomorrow.

**Comment by dehann** [comment]
thanks!
