### ISSUE TITLE
[FEATURE] maybe add timestamps to FactorDFG too

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#226]
not just variables

**Comment by Affie** [comment]
For L1: Does a factor not already have the associated N variables’s timestamp with it?
For solver data, I think it might be handy as a factor type. Say you have an uncertain association to a moving object.

**Comment by dehann** [comment]
also see #232

**Comment by GearsAD** [comment]
Alrighty - merged!
