### ISSUE TITLE
[FEATURE] addTags! function for post-hoc addition

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#229]
This might also involve IIF somehow, but it would be great to be able to add tags through the API after a variable already exists, e.g.:
```julia
addTags!(fg, :x4, [:RADAR; :LIDAR])
```

**Comment by dehann** [comment]
On second thought, that might mean full CRUD on tags?

**Comment by GearsAD** [comment]
Yes, but updateVariable should update the tags, I would suggest going that way for now. Would that work?

**Comment by dehann** [comment]
This issue also requires the common definitions for api or CRUD to be known.  Please add comments on the `verbNoun` definitions wiki here (link via docs):
https://www.juliarobotics.org/Caesar.jl/latest/dev/wiki/#Standardizing-the-API,-verbNoun-Definitions:-1
