### ISSUE TITLE
[FEATURE] filter on tags 

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#234]
Hi, not sure what the plan is around convenience functions, but perhaps we should look at supporting tag based searches as a general thing?  Not sure if this should be a secondary user call, or integrated with the general functions like `ls/lsf/getNeighbors/getVariableIds/getFactorIds/getVariables/getFactors/etc` from the get go?

I just came across a case where this would be mighty convenient -- check if any of the attached factors have the MAGNETOMETER tag:
```julia
ls(fg, :x1, tags=[:MAGNETOMETER;])
```

The idea in this case is to quickly filter out whether a particular type of tag has already been inserted (Prior factor in this case) before, which simplifies front end logic significantly.

**Comment by dehann** [comment]
also see #232

**Comment by dehann** [comment]
think we doubled up `ls` and `lsf` in this case---believe both should work---not sure if we need to be more specific here -- please comment if there are failure cases.

**Comment by dehann** [comment]
also both Variables and Factors can have tags.

**Comment by Affie** [comment]
That should already be possible:
```julia
function ls(dfg::G, regexFilter::Union{Nothing, Regex}=nothing; tags::Vector{Symbol}=Symbol[], solvable::Int=0)::Vector{Symbol} where G <: AbstractDFG
    return getVariableIds(dfg, regexFilter, tags=tags, solvable=solvable)
end
```
```julia
function getVariables(dfg::LightDFG, regexFilter::Union{Nothing, Regex}=nothing; tags::Vector{Symbol}=Symbol[], solvable::Int=0)::Vector{AbstractDFGVariable}

    # variables = map(v -> v.dfgNode, filter(n -> n.dfgNode isa DFGVariable, vertices(dfg.g)))
    variables = collect(values(dfg.g.variables))
    if regexFilter != nothing
        variables = filter(v -> occursin(regexFilter, String(v.label)), variables)
    end
    if solvable != 0
        variables = filter(v -> _isSolvable(dfg, v.label, solvable), variables)
    end
    if length(tags) > 0
        mask = map(v -> length(intersect(v.tags, tags)) > 0, variables )
        return variables[mask]
    end
    return variables
end
```

**Comment by Affie** [comment]
Sorry I see you actually mean filter the neighboring factors of a variable?
So is it actually `function getNeighbors(dfg::LightDFG, node::DFGNode; solvable::Int=0)::Vector{Symbol}` where you want the additional filters?

**Comment by Affie** [comment]
see #291 for tags filter added to `getFactors`, it just has to be extended to the rest of the functions

**Comment by dehann** [comment]
HI @Affie , sorry yes -- `getNeighbors`, perhaps also `listNeighbors` with `tags` filter is what I'm looking for.  Will add issue to Caesar.jl to better document this there, thanks!
