### ISSUE TITLE
SortDFG doesn't work with [:a, :b, :c]

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#241]

**Comment by dehann** [comment]
sortDFG definitely needs to be taken to the next level (again)

**Comment by Affie** [comment]
see natural less than defined here: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/48f4fa136c2ad0fc760e3cbf09677cf0f731c5f8/src/Common.jl#L476

**Comment by Affie** [comment]
We just need to figure out the API, then we can fix this in 0.6
