### ISSUE TITLE
[FEAT] add Threads.Condition field to VND

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#273]
Will allow user to "block" on a variable but immediately use the result after a notification (likely downsolve update), regardless of how far the total solver has progressed.

For example, image a graphinit operation is waiting on a previous variable somewhere.  If the previous variable is updated early in the downsolve on tree, then graph init can proceed without waiting for entire downsolve to complete first.

**Comment by dehann** [comment]
updated comment above

**Comment by Affie** [comment]
I think its a bit more complicated than just adding the field. I added commit to see how it would work https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/commit/61a988622964dc4501a03b74478093f2e7d84f8e

I'm wondering if a `Dict{Symbol, Condition}` (perhaps in the tree) will not be a better place to sort out the functionality first. If we add the field functions such as: compare, pack, copy get complicated and has to be reworked. 
Take the use case for example, IIF currently makes subgraph deepcopies. So the conditionals will not work. The subgraph can also exist on a different core/computer.

**Comment by dehann** [comment]
Can we skip the condition field during packing, and just create a new one when unpacking?

Also, do you know if `Condition` and `Thread.Condition` are interchangeable?

**Comment by dehann** [comment]
We should probably only use Threads.Condition and therefore lift our minimum Julia requirement to 1.2:
https://docs.julialang.org/en/v1/base/parallel/#Base.Threads.Condition
