### ISSUE TITLE
[BUG] findVariablesNearTimestamp

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#279]
Does not pass test consistently, sometimes returns [:b, :b]. 
Todo: have a closer look.

**Comment by dehann** [comment]
can we just add a distinct or unique function perhaps?

**Comment by dehann** [comment]
or ebmven union(list...)

**Comment by Affie** [comment]
just as a patch for the bug? I would have liked to know where it comes from. We don't need to fix it now. Just take note that there might be a bug in `findVariablesNearTimestamp` release v0.6 and we fix in v0.6.1
