### ISSUE TITLE
Check Cloud updateFactor! and validate neighbors 

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#281]
Confirm cloud updateFactor! works correctly with reduced interface.

**Comment by Affie** [comment]
What should happen if you update a factor with by adding new variables to it?
Surely its not the same factor any more and the label shouldn't be the same.
The same goes for changing the variables assigned to it.

**Comment by Affie** [comment]
Should `updateFactor!` error if `variableOrder` is changed with a message to delete it and add a new one.
So fields to be seen as "immutable":
- `label` 
- `variableOrder` 
- `timestamp`
- Its type

**Comment by GearsAD** [comment]
I took a look and in general CGDFG needs a significant refactor, there's a draft PR #285 of the template for the functions.

**Comment by Affie** [comment]
> yep, we just need to add validation to all the updates to error if variables are different
<sub>[View in Slack](https://caesarjl.slack.com/archives/CKGRFPZT8/p1581695107023000)</sub>

**Comment by GearsAD** [comment]
Removed that function and put the check in - https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/285/files#diff-60feee61df5ad89116b72980e992910eR224-R226

**Comment by Affie** [comment]
So this issue becomes:
Add validation to `updateFactor` to error if variables are different. ` error("Cannot update the factor, the neighbors are not the same.")`
- [ ] GraphsDFG
- [ ] LightDFG

**Comment by GearsAD** [comment]
Sounds like a plan - like the idea that we check that - links and their order are immutable, so good to fail.

**Comment by Affie** [comment]
It would be safest to make `_variableOrderSymbols` immutable. In the In-Memory drivers it is possible to change the variable order since its by reference.
