### ISSUE TITLE
Make DFG type stable

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#29]
Maybe target DFG v0.2.x to not have dynamic types such as `Union` or `Any`, for example here:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/aa7ac5df8cec93d134cd43c453949aecd663461e/src/services/GraphsDFG.jl#L54

See here:
https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-containers-with-abstract-type-parameters-1

**Comment by dehann** [comment]
If solveparams becomes an abstract type, we should just use templating for performance:
```julia
mutable struct MyType{T}
  solverParams::T
end
```

**Comment by dehann** [comment]
In that case:
```julia
mutable struct GraphsDFG{T} <: AbstractDFG
    g::FGType
    description::String
    nodeCounter::Int64
    labelDict::Dict{Symbol, Int64}
    addHistory::Vector{Symbol} #TODO: Discuss more - is this an audit trail?
    solverParams::T # Solver parameters
end
```

**Comment by GearsAD** [comment]
Sounds like a plan! Yep, it was just a placeholder, would be good to template that part

**Comment by GearsAD** [comment]
There's no inheritance, it would be nice to have that in AbstractDFG, but we'll just standardize a solverParms in every implementation of AbstractDFG.

**Comment by dehann** [comment]
still need to do #33 , but actually mostly finished the work with #31 already.
