### ISSUE TITLE
Where to specify fixed lag parameters in GraphsDFG?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#30]
Used to doing this:
```julia
fg.qfl = 8
fg.isfixedlag = true
```

Just want to hear what is the method going forward?

**Comment by GearsAD** [comment]
Yep! We can store those in `solverParams`, we just need to maybe make an abstract type for it (it's curreny ::Any), and that would go there. Ref: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/master/src/services/GraphsDFG.jl#L54

**Comment by dehann** [comment]
Okay, abstract type will be good via templating though:
see #29

**Comment by GearsAD** [comment]
:rocket:
