### ISSUE TITLE
Fix docs for v0.6

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#302]
- [x] Missing doc-strings
- [x] Broken links and doc-strings
- [x] Struct accessor names
- [ ] General updates

**Comment by dehann** [comment]
Hi @Affie , what help do you need for General Updates?  You mean read all the docs and make sure they are v0.6 complaint?

**Comment by Affie** [comment]
Small fix to docs #314 
If you quickly go though it and its ok we can close this. We can continuously improve as time goes on. Just want to make sure there are no major issues.

**Comment by dehann** [comment]
I think we must absolutely have the `!` in cases like this (#315 ):
https://juliarobotics.org/DistributedFactorGraphs.jl/latest/func_ref/#DistributedFactorGraphs.setTimestamp-Tuple{DFGVariable,Dates.DateTime}

**Comment by Affie** [comment]
>I think we really must have the ! in cases like this (#315 ):  

no, nothing is modified.
