### ISSUE TITLE
Does generated == replace the compare functions?

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#308]
Does this https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/master/src/services/CompareUtils.jl#L21-L28 replace the compare functions below?

**Comment by Affie** [comment]
In my mind, no. I don't think we should change the julia definition of ==. Think compare can still be used for skipping and specialized test? I left compare untouched as it is what IIF uses for tests.
However, I like the skipfield idea, but maybe as a keyword argument. We can also consider isaprox for iif tests.

**Comment by dehann** [comment]
so how about these two uses:
- A == B  ; and
- ==(A,B, skip=[:bob])

**Comment by Affie** [comment]
I would then suggest API of == and `isapprox`/`≈`  with both ignore.
following julia on `isapprox` but with ignore added.

**Comment by GearsAD** [comment]
:+1: for == ignore.

We just use the ignore for tests at the moment and I don't want us to break general use-cases - so it should be fine to just use the ==(..., ignore=[:adam]) there.

**Comment by dehann** [comment]
so how about then also having:
- `≈(A, B, ignore=[:thing])`

**Comment by dehann** [comment]
this may influence #285

**Comment by dehann** [comment]
xref #307

**Comment by Affie** [comment]
Also verbose flag for listing the fieldname it fails on.

**Comment by dehann** [comment]
Keep in mind @Affie  built this with `@generated` macro, and I understand the fieldname only during verbose is easiest (no fancy messages).

**Comment by dehann** [comment]
We need verbose to fix #293
