### ISSUE TITLE
Remove v0.6 deprecated code

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#323]
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/8aaead32e95df1c43e7e191271ce210b2f760ebc/src/Deprecated.jl#L7-L34

Left in on master as a last change. It will be removed completely with v0.6.

Feel free to update the list.

**Comment by dehann** [comment]
that sounds good thanks!
