### ISSUE TITLE
do we have a replacement for `ls2`?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#332]
Old use case, but might be nice to have something similar:

```julia
julia> ls2(fg, :x1)
[:x0; :x2; :l1]
```

**Comment by Affie** [comment]
Do make it clear `ls2` returns the neighboring variables to a variable (distance 2).
Perhaps we could add a filter to `getNeighborhood` to only return variables or factors.
