### ISSUE TITLE
Drop jld2 support and replace with FileDFG approach

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#35]
Striving for a common serialization strategy, maybe best to store data through the common serializer in a file.  The suggested strategy is perhaps a text file that is JSON encoded, which allows for any (possibly strange) data packing inside each variable and factor.  Can leverage some of the traditional protobuf packing/unpacking code while staying flexible for future changes.

This is similar to how the internet deals with data and MIME types.

Tangential: also see JuliaRobotics/IncrementalInference.jl#312

**Comment by dehann** [comment]
Maybe JuliaDB is best for this, see #38

**Comment by dehann** [comment]
Also see #42

**Comment by mc2922** [comment]
+1

**Comment by GearsAD** [comment]
Closing this as FileDFG is working
