### ISSUE TITLE
[bug] mergeVariableSolverData! maybe not doing PPE?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#358]
iifIntegrationTests failing on PPE after upgrading API to `mergeVariableSolverData!` from `mergeUpdateVariableSolverData!`

**Comment by Affie** [comment]
This is by design, the reasoning.
 
- `mergeVariableSolverData!`  variable solver data only
- `mergePPEs!`  PPEs only
- `mergeVariableData`  both.

We have different 'data' as:
- BigData
- SmallData
- VariableData
    - PPE
    - Solver Data

**Comment by dehann** [comment]
Acknowledged thanks, see related fixes in #356
