### ISSUE TITLE
[api] add mergeVariableData! for variable variable

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#359]
```julia
MethodError: no method matching mergeVariableData!(::DFGVariable{ContinuousScalar}, ::DFGVariable{ContinuousScalar})
```

another version already exists:
```julia
mergeVariableData!(dfg, sourceVariable)
```

related to #358

**Comment by Affie** [comment]
I wasn't convinced if it was a good idea not to have the dfg object. Say you want to merge from InMemory type to CloudType. 
The api on this level should perhaps always have the dfg object. Otherwise you get a variable from the cloud an update it expecting the cloud to update.

**Comment by dehann** [comment]
currently its in, lets see what happens here.
