### ISSUE TITLE
what to do with `_evalType` and several other encodings currently in IIF

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#36]
Trying to concentrate the pickling/unpickling, serialization/deserialization, packing/unpacking, encoding/decoding functions:

- [x] [`IIF/evalType`](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/5650955bda454251c1855dd0380e99ee249b78fc/src/FGOSUtils.jl#L506)
- [x] [`IIF/getpackedtype`](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/5650955bda454251c1855dd0380e99ee249b78fc/src/DispatchPackedConversions.jl#L91)
- [x] [`IIF/convert2packed...`](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/5650955bda454251c1855dd0380e99ee249b78fc/src/DispatchPackedConversions.jl#L121)
- [x] [`IIF/encodefg`](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/5650955bda454251c1855dd0380e99ee249b78fc/src/DispatchPackedConversions.jl#L154)
- [x] convert methods such as for example [`IIF/convert(::Type{Packed...}...`](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/5650955bda454251c1855dd0380e99ee249b78fc/src/DispatchPackedConversions.jl#L18)

**Comment by GearsAD** [comment]
In CloudgraphsDFG I was able to get by only using `IncrementalInference.decodePackedType`. Let me check on whether we can do an end-to-end solve with the CG driver, if so, I'd like to remove all the extraneous functions from IIF.

**Comment by dehann** [comment]
cc @Affie

**Comment by Affie** [comment]
Can be removed: 
- `IIF/encodefg` already removed and just a comment.
- `IIF/convert2packed...` not used anywhere
- `IIF/getpackedtype` looks like just an export without any functions
- `IIF/evalType` In deprecated and looks like its not called

**Comment by Affie** [comment]
> convert methods such as for example IIF/convert(::Type{Packed...}...

This is the core that is needed and has to be provided for every type.

**Comment by dehann** [comment]
must add this to docs:
https://juliarobotics.org/Caesar.jl/latest/concepts/adding_variables_factors/

we are already doing this for all types in IIF/RoME/Caesar :-)

**Comment by dehann** [comment]
`_evalType` is still used by ZMQ interface in Caesar.  This should be updated toward a standardized MsgEndpoint interface.
