### ISSUE TITLE
Consolidate copySubgraph functions (currently 5)

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#364]
Tried so hard to refactor and remove this, but this hacky subgraph function keeps coming back ... sigh -- see #363 

https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/c07421b56ce2e0cfac541ed8e8805ea869787848/src/needsahome.jl#L7-L66

**Comment by Affie** [comment]
@dehann What do you mean? Is this not your function added sometime around #248? I’ve never seen another one, but maybe i missed it.

**Comment by dehann** [comment]
There are currently 5 copySubgraph functions in existence

see #250, #300

**Comment by dehann** [comment]
Continue discussion at #300
