### ISSUE TITLE
CloudGraphsDFG does not solve

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#378]
State machine iter runs to 500

**Comment by GearsAD** [comment]
It looks like copying locally does not cause the issue, so it seems to be how IIF is handling it.

**Comment by GearsAD** [comment]
Proposed fix in #386 and requires https://github.com/JuliaRobotics/IncrementalInference.jl/pull/686.

It looks like the initialization wasn't being persisted. Keeping this as a WIP until the morning.

**Comment by Affie** [comment]
Should be fixed now. 

- [ ] Confirm with IIF tests
