### ISSUE TITLE
Finally deprecate GraphsDFG

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#398]
Lets just keep a todo list of what is broken:
- [ ] GraphsDFG should have used the the Dict storage model (not the Array model as was done), see here:
  - https://github.com/JuliaRobotics/IncrementalInference.jl/blob/fa574e9d06538512e76bc4561f2e1cd62f158cea/src/FactorGraphTypes.jl#L27
- [ ] #286, can most likely be fixed by the Dict storage model 
- [ ] #328 _internalId should be taken out 

Deprecate warn in DFG v0.8.0 and remove in DFG v0.9.0 

cc @Affie , @GearsAD

**Comment by Affie** [comment]
Ok GraphsDFG is moved to attic, but still included DFG with a do not use warning. 
Also it is not tested anymore.
