### ISSUE TITLE
[FEAT] listSolveKeys

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#400]
```julia
julia> listSolveKeys(fg)
:default
:parametric
:graphinit
:treeinit
:reference
```

**Comment by Affie** [comment]
To fit with the rest of the API, I made a per variable list as: `listVariableSolverData(dfg::AbstractDFG, variablekey::Symbol)`
Dit you have a fg wide on in mind? Or should it maybe return a dictionary of solvekey=>label

**Comment by dehann** [comment]
> `listVariableSolverData`

Oh cool thanks, did not know about that.

> Did you have a fg wide on in mind?

Yes, that was the idea -- would a "union" of all solveKeys available somewhere in the graph.  Havne't though on how to return that to user other just a vector.

> Or should it maybe return a dictionary of solvekey=>label

This could be one way to go yeah, where you get dict such that keys(dict) == listSolveKeys.  I think the idea with verb `list` is to always return a vector, right?   So we should use a different verb for returning dict of solveKeys and which variables contain them -- perhaps `buildSolveKeysDict`, or `findSolveKeysDict`?

**Comment by Affie** [comment]
Remember to look here https://juliarobotics.org/DistributedFactorGraphs.jl/latest/ref_api/ for verbs implemented.

**Comment by dehann** [comment]
I don't think we have resolved a union list return over the entire graph yet, so bumping to v0.9.0 -- if not we can close as part of v0.8.1.

**Comment by Affie** [comment]
You can currenlty have a vector of vectors with broadcasting:
```juila
listVariableSolverData.(fg, ls(fg))
2-element Array{Array{Symbol,1},1}:
 [:default]
 [:default]
```
But no listSolveKeys yet.

**Comment by dehann** [comment]
oh, thats right -- and easy:
```julia
listSolveKeys(dfg) = union(listVariableSolverData.(dfg, ls(dfg))...)
```

**Comment by dehann** [comment]
and we already have the function, just tiding up in #538
