### ISSUE TITLE
Should this be Vector{Float64}

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#439]
@dehann, should this perhaps be Vector{Float64}?
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/5d62dc7f7542ae63075f16ee4bf99a8d0fe413a1/src/entities/DFGFactor.jl#L44

**Comment by dehann** [comment]
Yes, that is right `::Vector{Float64}` is sufficient.
