### ISSUE TITLE
REMOVE factorOperationalMemoryType from solverParams

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#441]
See description of required work here: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/425#issuecomment-624225618

issue is in response to having to merge #433 early and fix problems later.

## Background

More accurately, this field:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/d2f47c68eb86866786917176f2ed363a781a64b3/src/services/AbstractDFG.jl#L58

which in IIF case carries the value `CommonConvWrapper::UnionAll`

**Comment by dehann** [comment]
packing and unpacking during serialization should not store types or functions for serialization!  Methods should rather be implemented as converters and operate in context Main.

**Comment by Affie** [comment]
Just to be clear, `convert` is used, but I stored the wrapper type to convert to in solverParams. It made kind of sense since perhaps other algorithms would want to use different wrappers.

**Comment by dehann** [comment]
> perhaps other algorithms would want to use different wrappers

Overloading the converters using multi-dispatch will achieve the same thing, no?

also:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/440/files#r420369361

**Comment by Affie** [comment]
> Overloading the converters using multi-dispatch will achieve the same thing, no?

I wasn't able to find a way. but wanted to carry on so went with what I thought was best. Also I did't like `IncrementalInference.CommonConvWrapper` hardcoded in DFG.

**Comment by dehann** [comment]
This is easily fixed like so:
- f62ef858f
- https://github.com/JuliaRobotics/IncrementalInference.jl/pull/695/commits/0a53db115e286b995ff20c7b16d7304043a3c04b

**Comment by dehann** [comment]
> Just to be clear, convert is used, but I stored the wrapper type to convert to in solverParams

Hi @Affie , thanks -- after working through this and getting my head back in this space (took awhile) i see that is done, thanks for keeping that line going!

Turns out my hangup was misplaced in name but still valid in spirit -- but I feel a fix will quite easy to avoid storing the type (as with new fix linked above).
