### ISSUE TITLE
Updtate Custom pretty-printing 

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#448]
- [x] Its really not supposed to overload print #454
    - can have printVariable(dfg, label)
    - can have printFactor(dfg, label)
- [x] add  tests #454
- [x] move from needsahome.jl #454
- [x] show DFG #461
- [x] tests show DFG

**Comment by dehann** [comment]
cool, shorthand `verb(::Noun)` not working in this case.  Sounds good!

**Comment by Affie** [comment]
Something like this to start with?
![image](https://user-images.githubusercontent.com/6612981/81500569-4c0e9400-92d3-11ea-874e-ea7c3772e6b6.png)

**Comment by Affie** [comment]
update other cases to rather use multi-line show ::MIME"text/plain" and perhaps dfgplot
