### ISSUE TITLE
do we need this warning (retrieving serialization)?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#462]
```julia
┌ Warning: Retrieving serialization module from AbstractDFG - override this in the 'LightDFG{SolverParams,DistributedFactorGraphs.DFGVariable,DistributedFactorGraphs.DFGFactor} structure! This is returning Main
└ @ DistributedFactorGraphs ~/.julia/packages/DistributedFactorGraphs/LKg9S/src/services/Serialization.jl:201
```

**Comment by dehann** [comment]
I dont even think the error message is valid?  Factor types are not available in LightDFG module, so why overwrite an unpacking function there?

**Comment by dehann** [comment]
I'm getting thousands of printouts of this message when loading a FileDFG and not sure how to fix.

**Comment by Affie** [comment]
I think it’s this one: #141

**Comment by Affie** [comment]
Btw, it comes from this function: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/d7524b3e9d7b05dbb0392000e1a05820f68310a7/src/services/Serialization.jl#L200-L203

**Comment by Affie** [comment]
Decision was to remove functions completely and use Main directly. So, no
