### ISSUE TITLE
Should `_variableOrderSymbols` be immutable. 

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#464]
It would be safest to make `_variableOrderSymbols` immutable. In the In-Memory drivers it is possible to change the variable order since its by reference. 

The biggest impact is on:
`addFactor!(dfg::AbstractDFG, variableLabels::Vector{Symbol}, factor::F)`

I would like to get rid of that function in any case...

_Originally posted by @Affie in https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/281#issuecomment-628112313_

**Comment by dehann** [comment]
that sounds good to me!
