### ISSUE TITLE
solverParams as keyword 

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#475]
A mix of `solverParams` and  `params` was used as keywords.
Standardize to `solverParams`

**Comment by dehann** [comment]
Hi @Affie, could we make this a keyword deprecation warning and not an error perhaps please -- as per semver?
```julia
julia> fg = generateCanonicalFG_Kaess()
ERROR: keyword `params` is deprecated, please use solverParams
Stacktrace:
 [1] error(::String) at ./error.jl:33
```

**Comment by dehann** [comment]
thats also why this is failing:
https://travis-ci.org/github/JuliaRobotics/IncrementalInference.jl/jobs/690377230

**Comment by Affie** [comment]
I’ll update to warning. Just note that cgdfg didn’t have params as keyword so I’m not doing anything there. 

> thats also why this is failing:
> https://travis-ci.org/github/JuliaRobotics/IncrementalInference.jl/jobs/690377230

Its testing again master and will only pass once merged to master. 
Note: I also update RoME accordingly.

**Comment by dehann** [comment]
Got it thanks!
