### ISSUE TITLE
Validate Packing of `fnd.hypothesis` `.certainhypo` `.nullhypo`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#477]
Serializing factor nodes has newer fields relating to multihypothesis features and the serialization might be brittle or poorly organized in code.  Need to validate these factor conversions in DFG:
- `.hypothesis`
- `.certainhypo`
- `.nullhypo`

There is some interaction with IIF.CCW on this if i recall correctly.

Looks like current is missing new `.nullhypo`:

https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/a04c1493f199e417621220ab07f4e4e1aff240a7/src/entities/DFGFactor.jl#L42-L43

**Comment by Affie** [comment]
possibly related [IIF #699](https://github.com/JuliaRobotics/IncrementalInference.jl/issues/699)

**Comment by dehann** [comment]
Yes I think so, shall we punt this one to DFG v0.8.1?

**Comment by dehann** [comment]
On second thought, lets try fix for DFG v0.8.0...

**Comment by Affie** [comment]
Just dumping related structures here to help:
```julia
mutable struct GenericFunctionNodeData{T<:Union{PackedInferenceType, FunctorInferenceType, FactorOperationalMemory}}
    eliminated::Bool
    potentialused::Bool
    edgeIDs::Vector{Int}
    fnc::T
    multihypo::Vector{Float64} # likely to moved when GenericWrapParam is refactored
    certainhypo::Vector{Int}
    solveInProgress::Int
end
```

```julia
struct DFGFactor{T, N} <: AbstractDFGFactor
    label::Symbol
    timestamp::DateTime
    nstime::Nanosecond
    tags::Set{Symbol}
    solverData::Base.RefValue{GenericFunctionNodeData{T}}
    solvable::Base.RefValue{Int}
    _variableOrderSymbols::NTuple{N,Symbol}
end
```

```julia
mutable struct CommonConvWrapper{T} <: FactorOperationalMemory where {T<:FunctorInferenceType}
  ### Values consistent across all threads during approx convolution
  usrfnc!::T # user factor / function
  # general setup
  xDim::Int
  zDim::Int
  # special case settings
  specialzDim::Bool # is there a special zDim requirement -- defined by user
  partial::Bool # is this a partial constraint -- defined by user
  # multi hypothesis settings
  hypotheses::Union{Nothing, Distributions.Categorical} # categorical to select which hypothesis is being considered during convolution operation
  certainhypo::Union{Nothing, Vector{Int}}
  # values specific to one complete convolution operation
  params::Vector{Array{Float64,2}} # parameters passed to each hypothesis evaluation event on user function
  varidx::Int # which index is being solved for in params?
  measurement::Tuple # user defined measurement values for each approxConv operation
  threadmodel::Union{Type{SingleThreaded}, Type{MultiThreaded}}
  ### particular convolution computation values per particle idx (varies by thread)
  cpt::Vector{ConvPerThread}
end
```

**Comment by dehann** [comment]
> is hypothesis = multihypo
   
No they are different

> must nullhypo be added here to GFND?

Yes, should be added somewhere which will be persisted by serialization.

**Comment by dehann** [comment]
FYI v0.9.0 adds `GFND.nullhypo::Float64`

**Comment by Affie** [comment]
There are now 2 `nullhypo`s: In `CommonConvWrapper` and `GenericFunctionNodeData`
I just want to confirm they are 
- both needed 
- the same
I'm going ahead with the assumption they are the same.

**Comment by Affie** [comment]
see https://github.com/JuliaRobotics/IncrementalInference.jl/pull/862
