### ISSUE TITLE
Remove GraphPlot dependency (Optional only)

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#485]
In the spirit of keeping visualization and functional code separate, suggest making it optional

```julia
┌ Warning: Package DistributedFactorGraphs does not have GraphPlot in its dependencies:
│ - If you have DistributedFactorGraphs checked out for development and have
│   added GraphPlot as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with DistributedFactorGraphs
└ Loading GraphPlot into DistributedFactorGraphs from pr
```

Preferred usage would be:
```julia
using GraphPlot, DistributedFactorGraphs
```

**Comment by Affie** [comment]
> `using GraphPlot, DistributedFactorGraphs`

That is how it works.

If the issue is the warning, there is no good way to fix it. The package/Requres.jl manager needs a way to add optional packages to the toml with version numbers. I'll have a look if it was improved in the mean time.
