### ISSUE TITLE
Serialize smalldata to a blob-less entry in CGDFG

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#509]
Quirky decision, how about dropping the separate smalldata container, and only maintaining the `Data` plumbing but allow entries that do not have an associated `Blob`?  We can flag the `Entry` object as either having a `Blob` or not (as immutable field in an `entry`)?

We can use the `Entry.description::String` field to store a JSONed string that represents the `Smalldata` interface, and limit its size...

`Smalldata` functions are then fuss-free wrappers around `entries` without worrying about what data types, `MIME`, `Entry` or `Blob`.   

(bit like Macklemore, bought a broken keyboard):  I have a short string, please store the short string...

cc @GearsAD @Affie  

Related #403

**Comment by GearsAD** [comment]
Not a bad idea, I'm about to separate out the big data as separate nodes though, so that may make this difficult.

**Comment by GearsAD** [comment]
I guess we could still do it, we would just have to collect the entries around the node, but it would be a bit more difficult than a JSON blob inside the actual node.

**Comment by Affie** [comment]
It fits in with why I originally created the `AbstractBigDataEntry`  (think to be renamed `AbstractDataEntry`) in our application.
I just stored the data in a custom structure directly. For example, tags were something like:
```julia
struct TagData <: AbstractDataEntry
    key::Symbol
    family::String
    tagids::Vector{Int}
    bTt
end
```
The problem was a concern that the payload could get too big. That's why the in-memory data store was created. I don't like and never used `smalldata` because of the `String`, but it can perhaps be consolidated as:
```julia
struct SmallData <: AbstractDataEntry
    key::Symbol
    data::String
   #OR 
    smallDataDict::Dict{String, String}
end
```

**Comment by dehann** [comment]
Affects JuliaRobotics/Caesar.jl#514

**Comment by dehann** [comment]
we could if we really wanted to store something like this using a combo of the `BlobEntry.description`, `BlobEntry.metadata`, and `BlobEntry.mimeType` fields.

**Comment by dehann** [comment]
Also,
```julia
julia> UUID("00000000-0000-0000-0000-000000000000")
UUID("00000000-0000-0000-0000-000000000000")
```
