### ISSUE TITLE
Regexes need to be double-escaped in CGDFG ls call

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#521]
This is a Neo4j quirk - for a regex like 'x\d', Neo4j requires that we send 'x\\d'. This may affect more complex regexes so I'm hoping Neo4j is consistent.

Reference this issue if any complex regex issues arise.

**Comment by dehann** [comment]
ah that is quirky — will do and might be a Neo4j.jl thing...
