### ISSUE TITLE
Consolidate the packing functions between Serialization.jl and CGDFG

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#525]
For performance and for query building they have been separated but the Serialization.jl functions should not save everything as strings so the two can be consolidated.

**Comment by dehann** [comment]
one day, promise one day, Distributions.jl types will have non-naive string serialization

**Comment by GearsAD** [comment]
Hahaha, that would be the best day ever.

**Comment by Affie** [comment]
This may help https://github.com/JuliaData/StructTypes.jl

**Comment by dehann** [comment]
just an fyi that i recently started removing stringafied Distributions.jl packing.  There is now a more sensible JSON version coming into focus.  See code for details
