### ISSUE TITLE
change Singleton / Pairwise to  AbstractPrior / AbstractRelativeFactor

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#533]
Or something similar, we can discuss here

# Also see

- https://github.com/JuliaRobotics/IncrementalInference.jl/issues/783

**Comment by dehann** [comment]
https://github.com/JuliaRobotics/IncrementalInference.jl/issues/783#issuecomment-660138828

**Comment by Affie** [comment]
The applicable code:
```julia
##==============================================================================
## Abstract Types
##==============================================================================

abstract type InferenceType end
abstract type PackedInferenceType end
abstract type FunctorInferenceType <: Function end
abstract type FactorOperationalMemory <: Function end
abstract type FunctorSingleton <: FunctorInferenceType end
abstract type FunctorPairwise <: FunctorInferenceType end
abstract type FunctorPairwiseMinimize <: FunctorInferenceType end
```
If a `FunctorSingleton` is always a prior, I would suggest 'Prior' then. It might be less of a learning curve to stick with familiar names? It took me a while to figure out what it was.

Also is the naming of `Functor` needed in  `FunctorInferenceType` and `FunctorSingleton`
maybe it can be reduced to 'AbstractPriorFactor` or even `AbstractPrior` and `AbstractRelativeFactor` ?

**Comment by dehann** [comment]
Yes, these two sound best to me -- let's do that:

> `AbstractPrior` and `AbstractRelativeFactor`

**Comment by GearsAD** [comment]
Personally I like simpler/shorter, `AbstractPrior` and `AbstractRelativeFactor` sound like a plan

**Comment by dehann** [comment]
Lets do a deprecation cycle on the names because RoME and Caesar are both using Singleton and Pairwise abstracts at the moment.  So basically just create the new ones next to it and place those ones in the Deprecated.jl file.
