### ISSUE TITLE
[REQUEST]: swap squares and circles when drawing dot of dfg object

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#56]
The SLAM community seem to prefer factors as squares and variables as circles.  At some point we should maybe just swap the picture.  Relating to graphviz visualization.

**Comment by sam-globus** [comment]
Can do - just a swap here: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/master/src/GraphsDFG/services/GraphsDFG.jl#L9-L10

**Comment by sam-globus** [comment]
I'm calling this: square peg, round issue
