### ISSUE TITLE
FEATURE lsWho, lsfWho

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#58]
Add methods that gives back all factor labels that fit the bill:
- [x] `lsWho(fg, :Pose3)`
- [x] `lsfWho(fg, :Point2Point2)`

return type `::Vector{Symbol}`

**Comment by dehann** [comment]
hey @nicrip, this might be a fun one to try early on.

**Comment by dehann** [comment]
complement to:
![Screenshot from 2019-07-08 13-46-37](https://user-images.githubusercontent.com/6412556/60856287-a3843500-a1d4-11e9-8932-54b737bfc388.png)

**Comment by Affie** [comment]
@dehann I quickly added something for this: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/commit/0a1053483705a2f33f5cb3bf08709e64e37d1089
Is it what you had in mind?

**Comment by dehann** [comment]
HI @Affie, yes that is great thanks!  We could also do with the types directly (in addition to Symbol):
```julia
lsWho(fg, Pose3)
```
Did you want to merge the jt/deveop branch at some point or cherry pick a separate PR from it?  I'm happy to merge stuff, as long as tests do a good job.

**Comment by Affie** [comment]
Ok, that shouldn't be a problem to do. Its a bit harder to test though. 
If you want it earlier we can cherry pick, it is mostly separate commits.
The develop branch has breaking changes and I had it in mind as v0.4.0. I just need some input from you and Sam.

**Comment by dehann** [comment]
We could even go as far as:
```julia
ls(fg, Pose2Point2BearingRange)
lsf(fg, Pose2Point2BearingRange)

ls(fg, Pose2)
```
