### ISSUE TITLE
Always implement minimum standard Interface <: AbstractBlobEntry

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#594]
All instances of AbstractDataEntry should at minimum implement:
```julia
label::Symbol
id::UUID
blobstore::Symbol # Perhaps this should rather be a Dict{Symbol, Symbol}?
hash::String # Probably https://docs.julialang.org/en/v1/stdlib/SHA
origin::String # E.g. user|robot|session|varlabel
description::String
mimeType::String
createdTimestamp::ZonedDateTime # of when the entry was created
```

Which will allow easy transfer between the different blob store locations and standard their use.

**Comment by dehann** [comment]
xref #586

**Comment by dehann** [comment]
also see:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/afd4e4154c053ff3d2e37fe965bf2e25f300a574/src/DataBlobs/entities/AbstractDataEntries.jl#L23-L50

**Comment by dehann** [comment]
xref #579

**Comment by Affie** [comment]
I do not agree. There should be no need for other blob store entries. `BlobStoreEntry` is the only one and should be generic enough. If it is not is should be updated.

**Comment by dehann** [comment]
If only one is needed then that is even better.  I'm just looking through the code trying to fix bugs (`loadDFG!` is breaking on `BlobStoreEntry` this morning) and see there are multiple `Entry`-s...

So we can remove `MongodbDataEntry` (deprecate)?

**Comment by Affie** [comment]
I left `MongodbDataEntry` there until it finds a replacement. Its the way I've been using it and for me a very convenient way to work with it. I would like to keep the InMemoryEntry though. 
I think serialization can support only the blob store entries (for now at least). It's kind of just shifting the problem to the blob stores.

**Comment by dehann** [comment]
there will only be one

**Comment by GearsAD** [comment]
Highlander rule!
