### ISSUE TITLE
solveKey or solverKey

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#599]
> I think Sam went with solverkey

Yeah, that needs to be fixed too.

_Originally posted by @dehann in https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/565#issuecomment-673040254_

**Comment by dehann** [comment]
I think it should be `solveKey` since the same solver can be run many times (e.g. `:default_0, :default_1, :parametric_2, :parametric_7`) which probably makes `solverKey` less fitting.
