### ISSUE TITLE
What happened to listSolvekeys?????

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#608]
Deprecation warning or something? 
```julia
julia> listSolvekeys(fg)
ERROR: UndefVarError: listSolvekeys not defined
Stacktrace:
 [1] top-level scope at REPL[5]:1
```

**Comment by Affie** [comment]
I think you renamed it to `listSolveKeys`
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/60ba70fdf026d995e727f72ef021db10835a5c2e/src/services/AbstractDFG.jl#L509

**Comment by Affie** [comment]
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/21d238ffcf0f6d5a2f89ea10a75df320d43e4d12/src/Deprecated.jl#L19
