### ISSUE TITLE
Add comprehensive FileDFG test

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#621]
Test all the things!

![image](https://user-images.githubusercontent.com/6854507/90320023-06c9b600-df03-11ea-96b2-30952e026ac4.png)

**Comment by Affie** [comment]
![image](https://user-images.githubusercontent.com/6612981/90335120-a7d37200-dfd2-11ea-95c7-7ad98f0be443.png)

**Comment by GearsAD** [comment]
Haha :+1:
