### ISSUE TITLE
possible to get parameters in function docs?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#623]
Hi, looks like Documenter is not linking all the possible arguments with the current layout -- im trying to find the correct `mimeType` :heavy_check_mark: syntax:
![Screenshot from 2020-08-16 18-24-20](https://user-images.githubusercontent.com/6412556/90345341-d7dc3e80-dfed-11ea-92f1-ca00c022ba58.png)

Available data in the mean time:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/579#issue-675520130

**Comment by dehann** [comment]
also note new documentation in Caesar.jl docs:
https://juliarobotics.org/Caesar.jl/latest/concepts/interacting_fgs/#Adding-A-FolderStore

**Comment by Affie** [comment]
We can just use `$(METHODLIST)`
