### ISSUE TITLE
FileDFG is not serializing some fields correctly

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#624]
The following fields need to be ignored to compare factors after deserialization.

Some are unavoidable (timezones), but multihypo, eliminated, and potentialused should be encoded properly.
```
for fact in lsf(dfg)
    @test compareFactor(getFactor(dfg, fact), 
        getFactor(retDFG, fact),
        skip=[
            :hypotheses, :certainhypo, :multihypo, # Multihypo
            :eliminated, 
            :timezone, :zone, # Timezones
            :potentialused])
end
```

**Comment by Affie** [comment]
xref #477

**Comment by Affie** [comment]
Potentially fixed by https://github.com/JuliaRobotics/IncrementalInference.jl/pull/862
