### ISSUE TITLE
make sure the Nouns, tags vs labels, are used properly

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#626]
e.g.
```julia
addVariable!(fg, label, varType, tags=[:POSE;])
```

see Noun definitions:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/wiki/Standard-Definitions-of-API-via-verbs-and-set-theory#noun-object

**Comment by Affie** [comment]
At least partially address by #629

**Comment by Affie** [comment]
I haven't seen the wrong usage in a while, I think we can close this and open specific issues if we find more.
