### ISSUE TITLE
Add regex filter for solve keys in listSolveKeys 

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#641]
MWE
```julia
using IncrementalInference
fg = generateCanonicalFG_Kaess()
[solveTree!(fg, storeOld=true for i in 1:3];

listSolveKeys(fg)
# :graphinit, :default, :default_0, :default_1, :default_2

listSolveKeys(fg, r"default_\d+") |> sortDFG
# Empty Set{Symbol}()
```

Should the regex filter not produce a list?
```julia
# [:default_0, :default_1, :default_2]
```

**Comment by Affie** [comment]
> Should the regex filter not produce a list?

Doesn't look like it:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/e30c7ededb569286f746be384e67acd6f1850c69/src/services/AbstractDFG.jl#L523-L535

**Comment by Affie** [comment]
Maybe try:

`filter(contains(r"default_\d+"), string.(listSolveKeys(fg)))`

**Comment by dehann** [comment]
thanks, yep that is the workaround i’m using, however, the current api does accept regex but does not seem to work properly.  We should probably make this consistent with ‘ls’ regex filter pattern argument and workflow.  

We can probably just include this filter line inside the listSolveKeys function, and make sure it returns a list of ::Symbol?  I’m not sure if regex works directly on Symbol...

**Comment by Affie** [comment]
It's probably better to have 2 filters:
- `filterVariables` filter as the function you wrote 
- `filterSolveKeys` additional `Symbol.(filter(contains(r"default_\d+"), string.(listSolveKeys(fg))))`

And no, regex doesn't work on Symbols
