### ISSUE TITLE
What API to get "PackedFactorType" from "FactorType"

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#659]
Which function should be used downstream for this?  Closest I can find is the reverse in `services/Serialization.jl:decodePackedType`?  This used to just be a converter `convert(PackedInferenceType, Pose2Pose2) == PackedPose2Pose2`, looks like that might have been removed?

```julia
julia> convert(PackedInferenceType, LinearConditional(Normal()))
ERROR: MethodError: Cannot `convert` an object of type LinearConditional{1,Normal{Float64}} to an object of type PackedInferenceType
Closest candidates are:
  convert(::Type{S}, ::T) where {S, T<:CategoricalArrays.CategoricalValue} at /home/dehann/.julia/packages/CategoricalArrays/0ZAbp/src/value.jl:68
  convert(::Type{T}, ::T) where T at essentials.jl:171
Stacktrace:
 [1] top-level scope at REPL[202]:1
```

**Comment by Affie** [comment]
> This used to just be a converter...

The only I know of is `convert(PackedFunctionNodeData{packtype}, getSolverData(f))`

Was this pre dfg? This is the first reference I can find.
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/commit/a9ca114a4bb077b44086718169f3ff9065e8a720
