### ISSUE TITLE
Variables shouldn't need to have a :default key for VariableNodeData during deserialization

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#698]
If there isn't a :default entry, the variable fails to deserialize.

Not the greatest error stack, but this is a start. I'm expecting it to be somewhere in Serialization.jl, near unpackVariable().

```
Error: Variable does not have solver data default
~/.julia/packages/DistributedFactorGraphs/zZz24/src/services/DFGVariable.jl:288
[ Info: MethodError(DistributedFactorGraphs.getSofttype, (nothing,), 0x0000000000006d5a)
```

**Comment by Affie** [comment]
This was fixed at some stage. Just guessing around v0.19
