### ISSUE TITLE
request change to order of addFactor! parameters

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#7]
The `addFactor!(sg, vars, factor; kwargs...)`, [the current implementation has order as `(sg, factor, vars)`](https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/f8694f4e1d99d4a63bf00698367eac374b7c6f74/src/services/GraphsDFG.jl#L65).

**Comment by GearsAD** [comment]
Can do!

**Comment by dehann** [comment]
I'm not sure which way round is best, but the legacy seems bigger motivation at this point.  There is some opportunity to finalize over the next couple of months.  Can use deprecation warnings and support both APIs if it turns out one is better than the other -- signatures are sufficiently unique.

**Comment by GearsAD** [comment]
#9 - done! Can you confirm and close?

**Comment by dehann** [comment]
Thanks!
