### ISSUE TITLE
Should we deprecate lsfWho in favor of just lsf

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#707]
_From PR discussion: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/705#discussion_r540034178_

> new name is:
> 'lsfTypes(fg, LinearRelative)'

> @dehann There is no function like that.
> Only lsfTypes(dfg) -> Return `Vector{Symbol}` of all unique factor types in factor graph.
>
> Did you perhaps mean just  `lsf` as the test just above that?
>
> Should we deprecate `lsfWho` in favour of just `lsf`

In this case `lsfWho` and `lsf` have almost identical functionality with different implementations. 
I would say we keep on only `lsf` for example `lsf(fg, LinearRelative)`

It can work if there is not a need for `lsf(fg, :LinearRelative)`

**Comment by dehann** [comment]
yeah that's fine, one modification: don't pass a Symbol, just pass the type (especially to resolve dispatch).
'lsf(fg, Pose2Pose2)'

This function already exists somewhere because i use it quite often.  Same goes for 
'ls(fg, Pose3)'

**Comment by dehann** [comment]
@Affie , its easy to just try and see that it is already working:

```julia
using RoME

fg = generateCanonicalFG_Hexagonal(graphinit=false);

julia> lsf(fg, Pose2Pose2)
6-element Array{Symbol,1}:
 :x3x4f1
 :x4x5f1
 :x5x6f1
 :x0x1f1
 :x1x2f1
 :x2x3f1
```

Please check if there are any other loose bits around so we can close this issue as needs be.  We definitely need to close out things like `lsfWho`.

**Comment by Affie** [comment]
- [ ] Deprecate `lsfWho` for just `lsf`
