### ISSUE TITLE
Tag v0.11.1

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#711]
@JuliaRegistrator register branch=release/v0.11

**Comment by dehann** [comment]
Hi @GearsAD , not sure if you know -- just in case.  The workflow file for TagBot will trigger new tag on closed issues (if there is anything to tag)

**Comment by dehann** [comment]
@GearsAD , okay think that is all of them:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/milestone/64?closed=1
