### ISSUE TITLE
Why do tests depend on IncrementalInference.jl ?

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#75]
Travis failing due to IIF dependency?
https://travis-ci.org/JuliaRobotics/DistributedFactorGraphs.jl/jobs/569362107

**Comment by dehann** [comment]
originally discovered from JuliaRobotics/RoME.jl#189

**Comment by dehann** [comment]
I know it was supposed to be temporary, but now we have IIF and RoME as permanent dependencies of DFG??

**Comment by GearsAD** [comment]
I thought it was taken out? May be in project file, let me check and remove if so

**Comment by GearsAD** [comment]
v0.3.1
