### ISSUE TITLE
CGDFG infinite recursion on deleteFactor

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#809]
The IIF current solver behavior replaces factors during `rebuildFactorMetadata`. This is an issue with CGDFG because deleting factors retrieves the factor. To fix this we should introduce a flag to suppress the `getFactor` call in `deleteFactor`, which is only used by IIF during `rebuildFactorMetadata`.

**Comment by dehann** [comment]
xref JuliaRobotics/IncrementalInference.jl#1424

**Comment by dehann** [comment]
think we can close this and resolve the DFGVariable[] IIIF 1424 issue over there?

**Comment by GearsAD** [comment]
Yep, merging
