### ISSUE TITLE
Migrate to new JuliaGraphs/Graphs.jl

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#814]
LightGraphs.jl is now archived, and future work is moving to JuliaGraphs/Graphs.jl

**Comment by Affie** [comment]
I looked at how we can do this and my suggestion is to create a GraphsDFG driver (again, but this one will just be a copy of LightDFG with name changes) and deprecate the LightDFG driver.
