### ISSUE TITLE
DFG v0.18 Laundry List

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#828]
- [x] Fix unpackFactor chicken egg issue,
  - #827 , 
  - JuliaRobotics/IncrementalInference.jl#1424,
- [x] Distributions and JSON (still going doing .write for smaller step),
  - JuliaRobotics/IncrementalInference.jl#1468 
- [x] Base64 on packed factor data,
  - #833
  - #834
- [x] LightGraphs -> Graphs maintenance
  - #826,
- [x] proper DFG alias and driver names,
  - #836
  - #845 
  - #837
  - #844 

----

Deferred: 
- #838
- User / Robot session creation optimization, #839

**Comment by GearsAD** [comment]
Added a [board for this on NavAbility](https://github.com/orgs/NavAbility/projects/34) to help track it. To discuss: we should make core projects in JuliaRobotics for public visibility.

**Comment by dehann** [comment]
Thanks, I just updated the Epic board.  One or two outstanding issues for DFG v0.18.0.  @GearsAD , did you want us to complete #839 for DFG v0.18.0 or defer to v0.18.1?

**Comment by dehann** [comment]
Deferred #839
