### ISSUE TITLE
Should we align User / Robot / Session in AbstractDFG

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#829]

**Comment by GearsAD** [comment]
Can you add some details to this? Just wondering how we action it as part of SDK release.

**Comment by dehann** [comment]
Hi Sam, that is a comment you  made if i recall, i just captured it during the meeting.  Can close if you don't think we need this any more.

**Comment by Affie** [comment]
I recall a question around if the julia DFG drivers' behavior should match that of the cloud when it comes to User/Robot/Session.
If this relates, it is worth some further thought.
