### ISSUE TITLE
Should we pull out Neo4JDFG as separate repo

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#838]

**Comment by Affie** [comment]
Perhaps a good idea, I'm having difficulty with `compat` and an unmaintained Neo4j:

> This project is no longer actively maintained and probably doesn't work with recent versions of Neo4j. PRs to fix aspects of its functionality are still welcome.

**Comment by jim-hill-r** [comment]
I am currently using this DFG and need to ensure it remains tested and compatible with updates at least for the time being.

**Comment by GearsAD** [comment]
Think we're good for now and we don't intend to pull it out anytime soon so closing this.
