### ISSUE TITLE
`inferdim` is not properly deprecated everywhere yet

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#847]

**Comment by dehann** [comment]
Hi @Affie , I assigned to you if you don't mind.  Sounds like you are closest to where the error was showing up, I have not seen this error happen my side before

**Comment by dehann** [comment]
FYI:

https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/fdd36d4242429cb9bde783703bd08ded187de865/src/Deprecated.jl#L17-L38

**Comment by Affie** [comment]
Ok so I found the bug, I'm just testing with IIF to see if it's okay there

**Comment by dehann** [comment]
Great thanks @Affie , think we're getting close on DFG v0.18
