### ISSUE TITLE
Include session/robot/user information in all graph types

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/DistributedFactorGraphs.jl#93]

**Comment by GearsAD** [comment]
This isn't necessary because IIF keeps track of the original driver.

**Comment by GearsAD** [comment]
Reopening as part of discussion with @Affie

**Comment by Affie** [comment]
We need a way to distinguish between different robots, sessions. Since all can use :x1,:x2,...  
Currently I use robotId and sessionId in visualization. 
It is also used for big data.

**Comment by Affie** [comment]
It has been added to GraphsDFG.
