### ISSUE TITLE
Missing field: BlobEntry.acquisitionTime

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#939]
TAC

- add field to data entry

**Comment by dehann** [comment]
xref:
- https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/985

**Comment by GearsAD** [comment]
Yep, I made it simply timestamp, that work for everyone?

The automated fields are lastUpdatedTimetstamp and createdTimestamp.

**Comment by dehann** [comment]
ah, missed the last comment -- so confirming:
- `BlobEntry.timestamp` is the same as `.acquisitionTimestamp`.
- `createdTimestamp` is as the name suggests.
- `lastUpdatedTimestamp` ... if a mutation happens for something specific like assigning a `.blobId` upon server upload.

**Comment by Affie** [comment]
I don't think `createdTimestamp` is intended to be set by the user but I'ts something interesting to consider in the offline use case.
