### ISSUE TITLE
saveDFG / loadDFG does not preserve order in .fncargvID field

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#95]
see JuliaRobotics/Caesar.jl#382

**Comment by GearsAD** [comment]
After testing this (unable to reproduce in a test graph), and then looking through the code, it seems that this _should_ be working as expected - https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/v0.3.2/src/FileDFG/services/FileDFG.jl#L101-L103

Can I look at the specific example?

**Comment by dehann** [comment]
yeah, upon closer inspection i see that this might also occur in function `buildSubgraphFromLabels`.  Haven't dug any deeper than that yet.

**Comment by dehann** [comment]
definitely in `buildSubgraphFromLabels` even before the test data was saved with `saveDFG`

**Comment by dehann** [comment]
xref JuliaRobotics/IncrementalInference.jl#354

**Comment by GearsAD** [comment]
Preliminary fix: `https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/tree/hotfix/v0_3_2_orderingissue`

**Comment by Affie** [comment]
It looks like Light, Symbol DFG does not have this error. I added a test for this https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/commit/fedcfceeeb35e797003d0847922c563d58c7be77

**Comment by GearsAD** [comment]
Tagged 0.3.3 with a fix.
