### ISSUE TITLE
Just one BlobEntry definition

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#955]
TAC
- Make just one consolidated type `BlobEntry` (best candidate to rename is `BlobStoreEntry`)
- Should we deprecate all `AbsractBlobEntry`s in favor of only `BlobEntry`

**Comment by GearsAD** [comment]
Yes, like the simplification.

**Comment by Affie** [comment]
There is no need for `AbstractBlobEntry` and it should just be replaced by struct `BlobEntry`
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/08b210969a48ff702b80d4f78e2079def49a2e01/src/entities/AbstractDFG.jl#L47
