### ISSUE TITLE
Add big data

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#97]

**Comment by Affie** [comment]
Store keys=>AbstractBigData vs. only keys
 
keys=>AbstractBigData
- To guarantee small payload: 
  - only dispatch to cloud on specific <:AbstractBigDataElement types. 
  - In memory (should) pass pointers around so it should ideally not matter.
- On delete variable: big data entry should be deleted externally

**Comment by Affie** [comment]
WIP PR https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/131

**Comment by GearsAD** [comment]
Updated in #228 using your AbstractBigDataPattern

**Comment by GearsAD** [comment]
AbstractBigDataEntry looks good - added a `GeneralBigDataEntry`, should support general use-cases - https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/228/files#diff-a9bf58a6f5bf50be944b4eb28d78862eR6-R12

**Comment by Affie** [comment]
Confirm if this is in CGDFG
