### ISSUE TITLE
variableType<:InferenceVariable  in VND

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/DistributedFactorGraphs.jl#979]
Going further, why did we have `VND{T <: InferenceVariable}`, and not just `DFGVariable{T}`?  This is more of a DFG consideration.

_Originally posted by @dehann in https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1228#issuecomment-826172622_

**Comment by Affie** [comment]
While we are breaking stuff, we should probably fix this if needed.

**Comment by dehann** [comment]
maybe, but we ran out of time for v0.20, so will have to wait for next round.

**Comment by dehann** [comment]
okay, i see it is part of:
- #894 

let me see if i can figure this one out quick

**Comment by dehann** [comment]
nope, just going to punt this.
