### ISSUE TITLE
missing field in DFG v0.20: BlobEntry.size

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#985]
Missing field `BlobEntry.size`:
- https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/3e2eca0f55314c6176bdd8506f1075fb16dd3910/src/DataBlobs/entities/BlobEntry.jl#L10

**Comment by dehann** [comment]
xref:
- https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/939

**Comment by dehann** [comment]
Hi @Affie , if v0.20.2, can we close this?

**Comment by Affie** [comment]
> Hi @Affie , if v0.20.2, can we close this?

Sorry typo

**Comment by Affie** [comment]
This is not in the API, so I'm not sure if/when it should be done.

**Comment by dehann** [comment]
done in v0.21.2 as optional field `::Union{Int, Nothing}`
