### ISSUE TITLE
Rename `PackedVariable` to `Variable`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#989]
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/a78b6d926f0e150224877866bdeebb6fa10bcaf2/src/entities/DFGVariable.jl#L181

**Comment by Affie** [comment]
I don’t see a need for PackedVariable in the near future. So would like to work towards just having the 3 levels:  `DFGVariableSkeleton`, `DFGVariableSummary`, and `DFGVariable`
